{
    "": {
        "Content-Transfer-Encoding": "8bit",
        "Content-Type": "text/plain; charset=UTF-8",
        "Language": "es_ES",
        "Language-Team": "Spanish <lfrancisco@coffeecup.com>",
        "Last-Translator": "Alberto Fernandez <afernandez@coffeecup.com>",
        "MIME-Version": "1.0",
        "PO-Revision-Date": "2012-10-26 12:49+0100",
        "POT-Creation-Date": "YEAR-MO-DA HO:MI+ZONE",
        "Project-Id-Version": "Web Form Form Builder",
        "X-Poedit-SourceCharset": "utf-8"
    },
    "  Show properties after insertion": "  Mostrar propiedades después de inserción",
    "\"Contact List\" associates drop-down options with email addresses that will receive form results. Place the visible label on the left and email address on the right, separated by a colon.\n\nFor example:\nSales:sales@coffeecup.com|#|http://www.coffeecup.com/help/articles/935/": "\"Lista de Contactos\" asocia las opciones de la lista desplegable con direcciones de email que recibirán los resultados del formulario. Sitúa la etiqueta visible a la izquierda y el email a la derecha, separados por dos puntos.\n\nPor ejemplo:\nVentas:sales@coffeecup.com|#|http://www.coffeecup.com/help/articles/935/",
    "2219 The element named \"%s\"  does not contain the value \"%s\" .\n\n": "2219 El elemento de nombre \"%s\" no contiene el valor \"%s\" .\n\n",
    "2219 The element named \"%s\" does not exist in the form.\n\n": "2219 El elemento de nombre \"%s\" no existe en el formulario.\n\n",
    "<!-- End of the body content for CoffeeCup Web Form Builder -->\n": "<!-- Fin del contenido para el body del CoffeeCup Web Form Builder -->\n",
    "<!-- End of the headers for CoffeeCup Web Form Builder -->\n": "<!-- Fin de los encabezados del CoffeeCup Web Form Builder -->\n",
    "<!-- Start of the body content for CoffeeCup Web Form Builder -->\n": "<!-- Inicio del contenido para el body del CoffeeCup Web Form Builder -->\n",
    "<!-- Start of the headers for CoffeeCup Web Form Builder -->\n": "<!-- Inicio de los encabezados del CoffeeCup Web Form Builder -->\n",
    "A check box with label %s already exists.": "Ya existe una casilla de verificación con etiqueta %s.",
    "A digital signature can be used to authenticate the identity of the sender of a message or the signer of a document.|#|http://www.coffeecup.com/help/articles/1113/": "Puede usarse una firma digital para autentificar la identidad del remitente del mensaje o del firmante de un documento.|#|http://www.coffeecup.com/help/articles/1113/",
    "A list option with label %s already exists.": "Ya existe una opción con etiqueta %s.",
    "A radio button with label %s already exists.": "Ya existe un botón de opción con etiqueta %s.",
    "AND": "Y",
    "Add Condition": "Añadir condición",
    "Add text to invoice": "Añadir texto a factura",
    "Allow Dates:": "Permitir fechas:",
    "Allowed Files:": "Archivos válidos:",
    "Alphanumeric": "Alfanumérica",
    "Alt:": "Alt:",
    "Alternative text": "Texto alternativo",
    "Always": "Siempre",
    "Amount": "Cantidad",
    "An element with name %s already exists.": "Ya existe un elemento con nombre %s.",
    "An empty check box label is not allowed.": "No se permite una etiqueta vacía para las casillas de verificación.",
    "An empty file type is not allowed.": "No se permite un tipo de archivo vacío.",
    "An empty hidden input name is not allowed.": "No se permite un nombre de campo oculto vacío.",
    "An empty hidden input value is not allowed.": "No se permite un valor de campo oculto vacío.",
    "An empty option label is not allowed.": "No se permite una etiqueta de opción vacía.",
    "An empty radio button label is not allowed.": "No se permite una etiqueta de botón de opción vacía.",
    "An empty regular expression is not allowed.": "No se permite una expresión regular vacía.",
    "Apply": "Aplicar",
    "Attach to mail": "Adjuntar al email",
    "Auto-complete": "Autocompletar",
    "Autofocus:": "Autofoco:",
    "Automatic (S-Drive only)": "Automático (solo S-Drive)",
    "Background:": "Fondo:",
    "Bank Account Number (USA)": "Número de cuenta bancaria (EEUU)",
    "Bank Routing Number (USA)": "Código de id. bancaria (EEUU)",
    "Based on the width value found in the Form Options tab, this element cannot be wider than %s.": "Basándonos en la anchura especificada en la pestaña Formulario, este elemento no puede ser más ancho de %s.",
    "Basic": "Básicos",
    "Because the drop-down menu is configured to be a required element, you cannot remove this option.": "Debido a que la lista desplegable está configurada como elemento obligatorio, no puedes borrar esta opción.",
    "Because the drop-down menu is configured to be a required element, you cannot select a default option.": "Debido a que la lista desplegable está configurada como elemento obligatorio, no puedes seleccionar una opción por defecto.",
    "Blackglass": "Cristal tintado",
    "Block quotes": "Boque de citas",
    "Bold": "Negrita",
    "Border:": "Borde:",
    "Bottom": "Inferior",
    "Button Color:": "Color botón:",
    "Canvas Color:*": "Color de lienzo:*",
    "Captcha": "Captcha",
    "Captcha Properties": "Propiedades del Captcha",
    "Captcha tests require form submitters to prove that they're human by re-typing a pair of words shown on the screen.\n\nChoose \"Automatic\" if you use S-Drive's automated form processing.\n\nChoose \"Manual\" if you export manually. You can get the keys for your domain at the reCAPTCHA website: www.recaptcha.org|#|http://www.coffeecup.com/help/articles/907": "Las pruebas de Captcha sirven para probar que las personas que van a enviar el formulario son humanas copiando un par de palabras que se muestran en pantalla.\n\nElige \"Automático\" si usas el procesamiento automático del formulario del S-Drive.\n\nElige \"Manual\" si exportas manualmente. Puedes obtener las claves para tu dominio en la página web reCAPTCHA: www.recaptcha.org|#|http://www.coffeecup.com/help/articles/907",
    "Captcha:": "Captcha:",
    "Center": "Centro",
    "Check ": "Casilla ",
    "Check Options": "Marca Opciones",
    "Check options": "Marca opciones",
    "Check out my CoffeeCup Form": "Échale un vistazo a mi formulario de Coffeecup",
    "Checkboxes": "Casillas verificación",
    "Choose Form Element": "Elegir elemento de formulario",
    "Choose Operator": "Elige operador",
    "Choose Value": "Elige valor",
    "Choose a Color": "Elige un color",
    "Choose one": "Elige una",
    "Clean": "Limpiar",
    "Clear Label:": "Etiqueta de borrado:",
    "Click here": "Haz clic aquí",
    "Click or drag to insert Checkboxes": "Haz clic o arrastra para insertar Casillas de verificación",
    "Click or drag to insert HTML": "Haz clic o arrastra para insertar HTML",
    "Click or drag to insert Plain Text": "Haz clic o arrastra para insertar Texto simple",
    "Click or drag to insert Radio Buttons": "Haz clic o arrastra para insertar Botones de opción",
    "Click or drag to insert a Date selector": "Haz clic o arrastra para insertar una Fecha",
    "Click or drag to insert a Drop Down menu": "Haz clic o arrastra para insertar una lista Desplegable",
    "Click or drag to insert a File Upload button": "Haz clic o arrastra para insertar un botón de Subir archivo",
    "Click or drag to insert a List Box": "Haz clic o arrastra para insertar una Lista",
    "Click or drag to insert a Number field": "Haz clic o arrastra para insertar un campo Número",
    "Click or drag to insert a Password field": "Haz clic o arrastra para insertar un campo Contraseña",
    "Click or drag to insert a Phone Number": "Haz clic o arrastra para insertar un Teléfono",
    "Click or drag to insert a Regular Expression Manager": "Haz clic o arrastra para insertar una Expresión regular",
    "Click or drag to insert a Section Break": "Haz clic o arrastra para insertar un Separador",
    "Click or drag to insert a Spacer": "Haz clic o arrastra para insertar un Espaciador",
    "Click or drag to insert a Text Area": "Haz clic o arrastra para insertar un Área de Texto",
    "Click or drag to insert a Text Field": "Haz clic o arrastra para insertar un Campo de Texto",
    "Click or drag to insert a Title/Heading": "Haz clic o arrastra para insertar un Título",
    "Click or drag to insert a Web Address field": "Haz clic o arrastra para insertar una Dirección Web",
    "Click or drag to insert an Email Address field": "Haz clic o arrastra para insertar un campo Email",
    "Click or drag to insert an Image": "Haz clic o arrastra para insertar una Imagen",
    "Click to show Captcha properties": "Haz clic para mostrar las propiedades del Captcha",
    "Click to show Footer properties": "Haz clic para mostrar las propiedades del Pie de página",
    "Click to show Header properties": "Haz clic para mostrar las propiedades del Encabezado",
    "Click to show Logo properties": "Haz clic para mostrar las propiedades del Logotipo",
    "Click to show Signature properties": "Haz clic para mostrar las propiedades de Firma",
    "Click to show Submit Button properties": "Haz clic para mostrar las propiedades del Botón de Enviar",
    "Color:": "Color:",
    "Comments": "Comentarios",
    "Configure this form element to have a price value and/or multiplier. A multiplier is basically the quantity of an item.|#|http://www.coffeecup.com/help/articles/957/": "Configura este elemento del formulario para tener un precio y/o un multiplicador. Un multiplicador es básicamente la cantidad de un ítem.|#|http://www.coffeecup.com/help/articles/957/",
    "Confirm": "Confirmar",
    "Contact List options must contain both a label and an email address separated by a colon.\nA default value has been placed in each improperly formatted option value.": "Las opciones de la Lista de Contactos deben contener una etiqueta y una dirección de email separadas por dos puntos.\nSe ha introducido un valor por defecto en cada opción incorrectamente formateada.",
    "Content:": "Contenido:",
    "Custom": "Personalizada",
    "Customize margins": "Personalizar márgenes",
    "Dashed": "A trazos",
    "Date": "Fecha",
    "Date Format:": "Formato:",
    "Date:": "Fecha:",
    "Decimals:": "Decimales:",
    "Delete": "Borrar",
    "Delete the selected element": "Borrar el elemento seleccionado",
    "Dotted": "Punteado",
    "Double": "Doble",
    "Drop Down": "Lista Desplegable",
    "Duplicate": "Duplicar",
    "Duplicate the selected element": "Duplicar el elemento seleccionado",
    "Elements": "Elementos",
    "Elements:": "Elementos:",
    "Email": "Email",
    "Email Address": "Email",
    "Enable": "Activar",
    "Enter HTML code to be inserted into your form. Try not to include anything that will break the design/function of the form.|#|http://www.coffeecup.com/help/articles/989/": "Introduce el código HTML que será introudcido en tu formulario. Intenta no incluir ningún elemento que rompa el diseño/funcionalidad del formulario.|#|http://www.coffeecup.com/help/articles/989/",
    "Error Message:": "Mensaje de error:",
    "Field Options:": "Opciones:",
    "File Type (extension)": "Tipo de Archivo (extensión)",
    "Font:": "Fuente:",
    "Footer": "Pie de Página",
    "Footer Properties": "Propiedades del Pie de Página",
    "Force steps of": "Aumentos de",
    "Form Options": "Formulario",
    "Form Properties": "Propiedades del formulario",
    "Form Total Multiplier": "Multiplicador total del formulario",
    "Form Width:": "Ancho:",
    "Format:": "Formato:",
    "Friendly Hint:": "Texto de ayuda:",
    "Get started by clicking or dragging elements here": "Comienza haciendo clic o arrastrando elementos aquí",
    "Groove": "Canal",
    "Group Name:": "Nombre grupo:",
    "Header": "Encabezado",
    "Header Properties": "Propiedades del Encabezado",
    "Height:": "Altura:",
    "Hidden Fields:": "Campos Ocultos:",
    "Hide Hints": "Ocultar Textos de Ayuda",
    "Hint Style:": "Estilo:",
    "Hover:": "Encima:",
    "Hyperlink": "Hipervínculo",
    "If you would like to attach the uploaded file to your notification message, please enable \"Notification message\" in the Email Notices section of the Settings menu.": "Si deseas adjuntar el archivo subido a tu mensaje de notificación, por favor activa \"Mensaje de Notificación\" en la sección Avisos por Email del menú Ajustes.",
    "If you would like to store uploaded files in your database, please enable \"Save to a MySQL database\" in the Saving Data section of the Settings menu.": "Si deseas almacenar archivos subidos en tu base de datos, por favor activa \"Guardar en una base de datos MySQL\" en la sección Datos del menú Ajustes.",
    "If:": "Si:",
    "Image": "Imagen",
    "Image Prefix:": "Prefijo de imagen",
    "Image:": "Imagen:",
    "Insert": "Insertar",
    "Inset": "Bajorrelieve",
    "Inside iFrame": "dentro de iFrame",
    "International": "Internacional",
    "Italic": "Cursiva",
    "Item Width:": "Ancho del Ítem:",
    "Justify": "Justificada",
    "Label": "Etiqueta",
    "Label Position:": "Posición etiquetas:",
    "Label:": "Etiqueta:",
    "Layout:": "Distribución:",
    "Left": "Izquierda",
    "Line Color:*": "Color de línea:*",
    "Link:": "Enlace:",
    "List Box": "Lista",
    "Logo": "Logotipo",
    "Logo Properties": "Propiedades del Logotipo",
    "Magical": "Mágicos",
    "Manual": "Manual",
    "Max. Errors:": "Máx. Errores:",
    "Max. File Size:": "Tamaño Máx.:",
    "Max. Length:": "Longitud Máx.:",
    "Max. Value:": "Valor Máx.:",
    "Max. Width:": "Ancho Máx.:",
    "Middle": "Central",
    "Min. Length:": "Longitud Mín.:",
    "Min. Value:": "Valor Mín.:",
    "Mobile UK": "Móvil RU",
    "Name": "Nombre",
    "Name:": "Nombre:",
    "Name<you@domain.com>": "Nombre<tu@dominio.com>",
    "New Page": "en una página nueva",
    "No Repeat": "No Repetir",
    "No White Spaces": "No Espacios en Blanco",
    "None": "Ninguno",
    "Not defined object type": "Tipo de objeto no definido",
    "Number": "Número",
    "Number fields cannot accept values with more than 6 decimals.": "Los campos de tipo Número no pueden aceptar valores de más de 6 decimales.",
    "OR": "O",
    "Off": "Desactivado",
    "One Column": "Una columna",
    "Only Letters": "Solo letras",
    "Only Lower case": "Solo minúsculas",
    "Only Numbers": "Solo números",
    "Only Upper case": "Solo mayúsculas",
    "Only display this element if the following conditions are met.|#|http://www.coffeecup.com/help/articles/972/": "Solo mostrar este elemento si se cumplen las condiciones siguientes.|#|http://www.coffeecup.com/help/articles/972/",
    "Option ": "Opción ",
    "Options:": "Opciones:",
    "Ordered list": "Lista ordenada",
    "Outset": "Altorrelieve",
    "Override Styles": "Estilos de anulación",
    "Padding:": "Padding:",
    "Password": "Contraseña",
    "Payment options must contain both a label and a value separated by a colon.": "Las opciones de pago deben contener una etiqueta y un valor separados por dos puntos.",
    "Payment options must contain both a label and a value separated by a colon.\nA default value has been placed in each improperly formatted option value.": "Las opciones de pago deben contener una etiqueta y un valor separados por dos puntos.\nSe ha introducido un valor por defecto en cada opción incorrectamente formateada.",
    "Payments:": "Pagos:",
    "Pen Color:*": "Color de Tinta:*",
    "Phone Number": "Teléfono",
    "Phone UK": "Telefóno RU",
    "Phone US": "Teléfono EEUU",
    "Pl": "Lp",
    "Placeholder:": "Indicador:",
    "Plain Text": "Texto simple",
    "Please allow at least 1 error to be displayed.": "Por favor permite por lo menos que se muestre 1 error.",
    "Please choose an option from each drop-down to complete the display rule.": "Por favor elige una opción de cada desplegable para completar la regla de visualización.",
    "Please enter a file size that is greater than 0kB.": "Por favor introduce un tamaño de archivo que sea mayor que 0kB.",
    "Please enter a file size that is lower or equal to 8192kB.": "Por favor introduce un tamaño de archivo que sea menor o igual que 8192kB.",
    "Please enter a valid URL.": "Por favor introduce una URL válida.",
    "Please enter a valid credit card number.": "Por favor introduce un número de tarjeta de crédito válido.",
    "Please enter a valid date (ISO).": "Por favor introduce una fecha válida (ISO).",
    "Please enter a valid date.": "Por favor introduce una fecha válida.",
    "Please enter a valid email address.": "Por favor introduce un email válido.",
    "Please enter a valid number.": "Por favor introduce un número válido.",
    "Please enter a valid value between {0} and {1}.": "Por favor introduce un valor válido entre {0} y {1}.",
    "Please enter a value between {0} and {1} characters long.": "Por favor introduce un valor que como mucho tenga entre {0} y {1} caracteres.",
    "Please enter a value equal to or greater than %s.": "Por favor introduce un valor mayor o igual que %s.",
    "Please enter a value equal to or greater than 30.": "Por favor introduce un valor igual o mayor que 30.",
    "Please enter a value equal to or less than %s.": "Por favor introduce un valor menor o igual que %s.",
    "Please enter a value equal to or less than the chosen maximum value of %s.": "Por favor introduce un valor mayor o igual que el valor máximo elegido %s.",
    "Please enter a value greater than or equal to {0}.": "Por favor introduce un valor mayor o igual que {0}.",
    "Please enter a value less than or equal to {0}.": "Por favor introduce un valor menor o igual que {0}.",
    "Please enter a value matching the regular expression.": "Por favor introduce un valor que cumpla la expresión regular.",
    "Please enter a value that is equal to or greater than the chosen minimum value of %s.": "Por favor introduce un valor que sea mayor o igual que el valor mínimo elegido %s.",
    "Please enter a value that is greater than the chosen minimum value of %s.": "Por favor introduce un valor que sea mayor que el valor mínimo elegido %s.",
    "Please enter a value that is greater than the step value of %s.": "Por favor introduce un valor que sea mayor que el valor de aumento %s.",
    "Please enter a value that is less than the chosen maximum value of %s.": "Por favor introduce un valor que sea menor que el máximo escogido %s.",
    "Please enter a value with a valid extension.": "Por favor elige un fichero con una extensión válida.",
    "Please enter at least {0} characters.": "Por favor introduce por lo menos {0} caracteres.",
    "Please enter no more than {0} characters.": "Por favor no introduzcas más de {0} caracteres.",
    "Please enter only digits.": "Por favor introduce solo dígitos.",
    "Please enter the same value again.": "Por favor introduce de nuevo el mismo valor.",
    "Please fix this field.": "Por favor corrige este campo.",
    "Please select an element to delete.": "Para borrar por favor selecciona un elemento.",
    "Please select an element to duplicate.": "Para duplicar por favor selecciona un elemento.",
    "Please select at least {0} options.": "Por favor selecciona al menos {0} opciones.",
    "Please specify a valid phone number.": "Por favor introduce un teléfono válido.",
    "Pleaser enter a value equal to or greater than the minimum height of %s": "Por favor introduce un valor que sea mayor o igual que la altura mínima %s",
    "Position:": "Posición:",
    "Price Input": "Precio",
    "Price Multiplier": "Multiplicador de precio",
    "Price:": "Precio:",
    "Private Key:": "Clave Privada:",
    "Properties": "Propiedades",
    "Public Key:": "Clave Pública:",
    "Quantity": "Veces",
    "Radio ": "Opción ",
    "Radio Buttons": "Botones de opción",
    "Read only": "Solo lectura",
    "Red": "Rojo",
    "Reg. Expression": "Expresión regular",
    "RegEx:": "Tipo:",
    "Regular": "Normal",
    "Regular Expression": "Expresión regular",
    "Regular expressions restrict fields to a certain format or set of characters. You can use a preset or define your own custom expression.|#|http://www.coffeecup.com/help/articles/940": "Las expresiones regulares restringen campos a un cierto formato o conjunto de caracteres. Puedes usar una expresión predefinida o personalizar una propia.|#|http://www.coffeecup.com/help/articles/940",
    "Repeat": "Repetir",
    "Repeat Horizontal": "Repetir horizontal",
    "Repeat Vertical": "Repetir vertical",
    "Require": "Obligatorias",
    "Required": "Obligatorio",
    "Reset Styles": "Restaurar estilos",
    "Ridge": "Cresta",
    "Right": "Derecha",
    "Same Page": "en la Misma Página",
    "Sample text": "Texto de ejemplo",
    "Save to server": "Guardar en servidor",
    "Section Break": "Separador",
    "Select a date": "Selecciona una fecha",
    "Select a file": "Selecciona un archivo",
    "Select an element and its editable properties will appear here.": "Selecciona un elemento y sus propiedades editables aparecerán aquí.",
    "Select an option": "Selecciona una opción",
    "Select options": "Selecciona opciones",
    "Show Element:": "Mostrar elemento:",
    "Side by Side": "Una al lado de la otra",
    "Signature": "Firma",
    "Signature Properties": "Propiedades de Firma",
    "Signature:": "Firma:",
    "Solid": "Continuo",
    "Spacer": "Espaciador",
    "Static": "Estáticos",
    "Store in database": "Almacenar en base de datos",
    "Style:": "Estilo:",
    "Submit": "Enviar",
    "Submit Button": "Botón de Enviar",
    "Table": "Tabla",
    "Target:": "Abrir:",
    "Text Area": "Área de texto",
    "Text Field": "Campo de texto",
    "Text to display for html element help.|#|http://www.coffeecup.com/help/articles/972/": "Texto a mostrar para la ayuda de elemento HTML.|#|http://www.coffeecup.com/help/articles/972/",
    "Text:": "Texto:",
    "The allowed file of type %s already exists.": "Ya existe el tipo de archivo permitido %s.",
    "The following characters are not valid:  & < > | \" \\ / : * ? ": "Los caracteres siguientes no son válidos: & < > | \" \\ / : * ? ",
    "The group name %s already exists": "Ya existe el grupo con nombre %s",
    "The group name can not be empty": "El nombre del grupo no puede ser vacío",
    "The maximum date %s is before the minimum date entered %s.": "La fecha máxima %s es anterior a la fecha mínima introducida %s.",
    "The maximum height allowed is %s.": "La altura máxima permitida es %s.",
    "The maximum padding bottom allowed is %s.": "El máximo padding inferior permitido es %s.",
    "The maximum padding left allowed is %s.": "El máximo padding izquierdo permitido es %s.",
    "The maximum padding right allowed is %s.": "El máximo padding derecho permitido es %s.",
    "The maximum padding top allowed is %s.": "El máximo padding superior permitido es %s.",
    "The maximum size allowed for a %s element is 195.": "El tamaño máximo permitido para un elemento %s es de 195.",
    "The maximum width allowed is %s.": "La anchura máxima permitida es %s.",
    "The minimum date %s is after the maximum date entered %s.": "La fecha mínima %s es posterior que la fecha máxima introducida %s.",
    "The minimum width allowed is %s.": "La anchura mínima permitida es %s.",
    "The name %s already exists": "El nombre %s ya existe",
    "The name property must begin with an uppercase or lowercase letter, and may contain digits, hyphens, underscores, and colons as well.": "La propiedad nombre debe empezar con una letra mayúscula o minúscula, y también puede contener dígitos, guiones, barra baja y dos puntos.",
    "The number of decimals specified for forced stepping must be equal to or less than the Decimals value. For example, if forcing steps of 0.25, the Decimals value must be 2 or greater.": "El número de decimales especificados para los aumentos debe ser igual o menor que el numero de decimales. Por ejemplo, si fuerzas aumentos de 0,25, el número de decimales debe ser 2 o mayor.",
    "The regular expression \"%s\" is invalid. Please check for proper syntax": "La expresión regular \"%s\" es inválida. Por favor comprueba que la sintaxis sea correcta.",
    "The step value must equally divide into the chosen range.": "El resto de dividir el valor máximo menos el valor mínimo entre el aumento debe dar cero.",
    "The value %s is not a valid step value.": "El valor %s no es un valor de aumento válido.",
    "Theme:": "Tema:",
    "This element cannot be selected as the form total multiplier because the element \"%s\" is already handling this property.": "Este elemento no puede ser seleccionado como el multiplicador total del formulario porque el elemento \"%s\" ya está manejando esta propiedad.",
    "This element must have a width value equal to or greater than 60.": "Este elemento debe tener una anchura mayor o igual que 60.",
    "This field is required.": "Este campo es obligatorio.",
    "Three Columns": "Tres columnas",
    "Title": "Título",
    "Title/Heading": "Título",
    "Top": "Superior",
    "Total Multiplier": "Multiplicador total",
    "Transparent": "Transparente",
    "Two Columns": "Dos columnas",
    "Type": "Tipo",
    "Unordered list": "Lista no ordenada",
    "Upload File": "Subir archivo",
    "Use Default Box Shadow": "Usa Box Shadow por defecto",
    "Use as Contact List": "Lista de contactos",
    "Use scripts at your own risk, because they can break the functionality of your form. To prevent damage to the app, scripts are only processed during preview and upload.|#|http://www.coffeecup.com/help/articles/989/": "Usa scripts con cuidado porque pueden romper la funcionalidad de tu formulario. Para prevenir daño a la app. los scripts sólo se procesan durante la vista previa y la subida.|#|http://www.coffeecup.com/help/articles/989/",
    "Using Display Rule": "Usando regla de visualización",
    "Value": "Valor",
    "Verify": "Verificar",
    "Web Address": "Dirección Web",
    "White": "Blanco",
    "Width:": "Anchura:",
    "Workflow": "Flujo de trabajo",
    "You currently have MySQL enabled and are attempting to decrease the number of decimal places. This will cause all data to be rounded down to the new decimal place value.": "Actualmente tienes activado MySQL y está intentando disminuir el número de cifras decimales. Esto provocará que todos los datos sean redondeados hacia abajo para adaptarse al nuevo valor de cifras decimales.",
    "You must provide a number for this value.": "Debes suministrar un número para este valor.",
    "You must provide a positive integer for this value.": "Debes suministrar un entero positivo para este valor.",
    "You must provide a positive number for this value.": "Debes suministrar un número positivo para este valor.",
    "You must provide a positive price for this value.": "Debes suministrar un precio positivo para este valor.",
    "You need to disable Contact List in order to use this functionality.": "Para poder usar esta funcionalidad necesitas desactivar la Lista de Contactos.",
    "You need to disable Payments in this control in order to use this functionality.": "Para poder usar esta funcionalidad, necesitas desactivar Pagos en este control.",
    "Your chosen Button Color may not display if button images are being used. You may need to remove the \"Regular\" image to see your Button Color.": "El color elegido para el Color del Botón puede que no se muestre si se están usando las imágenes del botón. Quizás necesites borrar la imagen \"Normal\" para ver tu Color del Botón.",
    "ZIP Code (USA)": "Código ZIP (EEUU)",
    "_cart_summary_": "_resumen_de_compra_",
    "_cart_total_": "_valor_total_compra_",
    "_form_invoicetext_": "_descripcion_importe_formulario_",
    "_form_price_": "_precio_formulario_",
    "_form_results_": "_resultados_del_formulario_",
    "_fromaddress_": "_direccion_del_remitente_",
    "_invoicetext": "_descripcion_importe",
    "_price": "_precio",
    "_submitted_": "_enviado_el_",
    "at a time": "de cada vez",
    "eBay Item ID": "Identificador de eBay",
    "is": "es",
    "is not": "no es",
    "none": "ninguno",
    "options to be checked": "opciones",
    "pixels": "píxeles",
    "plain text": "texto simple",
    "title/heading": "título",
    "to": "al",
    "you@domain.com": "tu@dominio.com"
}